version: "3.7"

volumes:
    informatica_data:
    postgres_data:

services:
  postgres:
    image: postgres:12-alpine
    hostname: postgres.${BASE_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports: 
      - 5432:5432
    env_file: 
      - .env.postgres

  informatica:
    image: ipc_lab/informatica:10.4.1
    hostname: informatica.${BASE_URL}
    volumes: 
      - informatica_data:/home/informatica
      - ./pg_service.conf:/tmp/pg_service.conf
    ports:
      - 7333:7333
      - 8095:8095
      - 6005-6008:6005-6008
      - 6013-6113:6013-6113
    env_file:
      - .env.postgres
    environment:
      - DOMAIN_ACTION=CREATE
      - PGSERVICEFILE=/tmp/pg_service.conf